/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg202102297.tugasakhir;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;


public class faulinaindri extends javax.swing.JFrame {
    public double row1, row2, row3, row4, row5;
    public int TotalSemua, uangkembalian; 
    public int daftar1=0, daftar2=0,daftar3=0, daftar4=0, daftar5=0;
    private Connection con;
    private Statement stat;
    private ResultSet res;
 
    //private Object Tabel;
    
   
    public faulinaindri() {
        initComponents();
        setTitle("Form Resto");
        koneksi();
        viewtable();
        
        
    }
    private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/resto", "root", "");
            stat = con.createStatement();
            JOptionPane.showMessageDialog(null, "Koneksi Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void addDatabase(String No,String Tanggal,String nama_makanan,String harga,String jumlah,String total,String total_transaksi, String bayar, String kembali) { 
        try {
            stat.executeUpdate("INSERT INTO tb_resto VALUE("
                    + "'" + No + "',"
                    + "'" + Tanggal + "',"
                    + "'" + nama_makanan + "',"
                    + "'" + harga + "',"
                    +"'" + jumlah + "',"
                    + "'" + total + "',"
                    + "'" + total_transaksi + "',"
                    + "'" + bayar + "',"
                    + "'" + kembali + "')"
            );
            viewtable();
            }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
}
     private void viewtable(){
          
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("No Transaksi");
        tb.addColumn("Tanggal");
        tb.addColumn("Nama");
        tb.addColumn("Harga");
        tb.addColumn("Jumlah");
        tb.addColumn("Total");
        tb.addColumn("Neto");
        tb.addColumn("Bayar");
        tb.addColumn("Kembalian");
        
        jTable2.setModel(tb);
        try{
            res = stat.executeQuery("SELECT*FROM tb_resto");
            while(res.next()){
                Object[] data ={
                    res.getString("No"),
                    res.getString("Tanggal"),
                    res.getString("nama_makanan"),
                    res.getString("harga"),
                    res.getString("jumlah"),
                    res.getString("total"),
                    res.getString("total_transaksi"),
                    res.getString("bayar"),
                    res.getString("kembali")
                };tb.addRow(data);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    

   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        btnBATAL = new javax.swing.JButton();
        btnKELUAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDAFTAR1 = new javax.swing.JTextField();
        txtHARGA2 = new javax.swing.JTextField();
        txtJUMLAH1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTOTAL1 = new javax.swing.JTextField();
        btnPROSES = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnHITUNG = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtTOTAL = new javax.swing.JTextField();
        btnBABI = new javax.swing.JButton();
        btnAYAM = new javax.swing.JButton();
        btnNASICAMPUR = new javax.swing.JButton();
        txtDAFTAR3 = new javax.swing.JTextField();
        txtDAFTAR2 = new javax.swing.JTextField();
        txtDAFTAR5 = new javax.swing.JTextField();
        txtDAFTAR4 = new javax.swing.JTextField();
        txtHARGA3 = new javax.swing.JTextField();
        txtHARGA4 = new javax.swing.JTextField();
        txtHARGA5 = new javax.swing.JTextField();
        txtHARGA1 = new javax.swing.JTextField();
        txtJUMLAH2 = new javax.swing.JTextField();
        txtJUMLAH3 = new javax.swing.JTextField();
        txtJUMLAH4 = new javax.swing.JTextField();
        txtJUMLAH5 = new javax.swing.JTextField();
        btnOKE2 = new javax.swing.JButton();
        btnOKE3 = new javax.swing.JButton();
        btnOKE5 = new javax.swing.JButton();
        btnOKE4 = new javax.swing.JButton();
        btnOKE1 = new javax.swing.JButton();
        txtTOTAL2 = new javax.swing.JTextField();
        txtTOTAL4 = new javax.swing.JTextField();
        txtTOTAL3 = new javax.swing.JTextField();
        txtTOTAL5 = new javax.swing.JTextField();
        txtBAYAR = new javax.swing.JTextField();
        txtKEMBALI = new javax.swing.JTextField();
        btnNASIGORENG = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnIKAN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnPESAN = new javax.swing.JButton();
        txtTANGGAL = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtNO = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        btnHAPUSRIWAYAT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnBATAL.setBackground(new java.awt.Color(204, 255, 204));
        btnBATAL.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnBATAL.setForeground(new java.awt.Color(0, 102, 0));
        btnBATAL.setText("BATAL");
        btnBATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBATALActionPerformed(evt);
            }
        });

        btnKELUAR.setBackground(new java.awt.Color(204, 255, 204));
        btnKELUAR.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnKELUAR.setForeground(new java.awt.Color(0, 102, 0));
        btnKELUAR.setText("KELUAR");
        btnKELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKELUARActionPerformed(evt);
            }
        });

        jLabel1.setText("Daftar Menu yang diorder :");

        jLabel2.setText("Nama ");

        jLabel3.setText("Harga");

        jLabel4.setText("Jumlah");

        jLabel8.setText("Total");

        btnPROSES.setBackground(new java.awt.Color(204, 255, 204));
        btnPROSES.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPROSES.setForeground(new java.awt.Color(0, 102, 51));
        btnPROSES.setText("Proses");
        btnPROSES.setBorder(null);
        btnPROSES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPROSESActionPerformed(evt);
            }
        });

        jLabel9.setText("Total Transaksi    : ");

        jLabel10.setText("Bayar               :");

        btnHITUNG.setBackground(new java.awt.Color(204, 255, 204));
        btnHITUNG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHITUNG.setForeground(new java.awt.Color(0, 102, 51));
        btnHITUNG.setText("Hitung");
        btnHITUNG.setBorder(null);
        btnHITUNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHITUNGActionPerformed(evt);
            }
        });

        jLabel11.setText("Kembali            :");

        txtTOTAL.setEditable(false);
        txtTOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTOTALActionPerformed(evt);
            }
        });

        btnBABI.setBackground(new java.awt.Color(204, 255, 204));
        btnBABI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBABI.setForeground(new java.awt.Color(0, 102, 51));
        btnBABI.setText("Paket 2");
        btnBABI.setBorder(null);
        btnBABI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBABIActionPerformed(evt);
            }
        });

        btnAYAM.setBackground(new java.awt.Color(204, 255, 204));
        btnAYAM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAYAM.setForeground(new java.awt.Color(0, 102, 0));
        btnAYAM.setText("Paket 3");
        btnAYAM.setBorder(null);
        btnAYAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAYAMActionPerformed(evt);
            }
        });

        btnNASICAMPUR.setBackground(new java.awt.Color(204, 255, 204));
        btnNASICAMPUR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNASICAMPUR.setForeground(new java.awt.Color(0, 102, 0));
        btnNASICAMPUR.setText("Paket 4");
        btnNASICAMPUR.setBorder(null);
        btnNASICAMPUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNASICAMPURActionPerformed(evt);
            }
        });

        txtJUMLAH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJUMLAH2ActionPerformed(evt);
            }
        });

        txtJUMLAH5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJUMLAH5ActionPerformed(evt);
            }
        });

        btnOKE2.setBackground(new java.awt.Color(204, 255, 204));
        btnOKE2.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btnOKE2.setForeground(new java.awt.Color(0, 102, 51));
        btnOKE2.setText("OKE");
        btnOKE2.setBorder(null);
        btnOKE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKE2ActionPerformed(evt);
            }
        });

        btnOKE3.setBackground(new java.awt.Color(204, 255, 204));
        btnOKE3.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btnOKE3.setForeground(new java.awt.Color(0, 102, 51));
        btnOKE3.setText("OKE");
        btnOKE3.setBorder(null);
        btnOKE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKE3ActionPerformed(evt);
            }
        });

        btnOKE5.setBackground(new java.awt.Color(204, 255, 204));
        btnOKE5.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btnOKE5.setForeground(new java.awt.Color(0, 102, 51));
        btnOKE5.setText("OKE");
        btnOKE5.setBorder(null);
        btnOKE5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKE5ActionPerformed(evt);
            }
        });

        btnOKE4.setBackground(new java.awt.Color(204, 255, 204));
        btnOKE4.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btnOKE4.setForeground(new java.awt.Color(0, 102, 51));
        btnOKE4.setText("OKE");
        btnOKE4.setBorder(null);
        btnOKE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKE4ActionPerformed(evt);
            }
        });

        btnOKE1.setBackground(new java.awt.Color(204, 255, 204));
        btnOKE1.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btnOKE1.setForeground(new java.awt.Color(0, 102, 51));
        btnOKE1.setText("OKE");
        btnOKE1.setBorder(null);
        btnOKE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKE1ActionPerformed(evt);
            }
        });

        txtKEMBALI.setEditable(false);

        btnNASIGORENG.setBackground(new java.awt.Color(204, 255, 204));
        btnNASIGORENG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNASIGORENG.setForeground(new java.awt.Color(0, 102, 51));
        btnNASIGORENG.setText("Paket 5");
        btnNASIGORENG.setBorder(null);
        btnNASIGORENG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNASIGORENGActionPerformed(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(153, 153, 153));
        jLabel22.setFont(new java.awt.Font("Imprint MT Shadow", 0, 48)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("~ Green Pondok ~");

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Pictures\\Saved Pictures\\ikan panggang.jpg")); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Ikan Panggang : Rp 25.000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Pictures\\Saved Pictures\\bipang.jpg")); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Babi Panggang : Rp 40.000");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel24)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(30, 30, 30))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(41, 41, 41)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIKAN.setBackground(new java.awt.Color(204, 255, 204));
        btnIKAN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIKAN.setForeground(new java.awt.Color(0, 102, 51));
        btnIKAN.setText(" Paket 1");
        btnIKAN.setBorder(null);
        btnIKAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIKANActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 153, 0));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Pictures\\Saved Pictures\\Ayam Rica-Rica.jpg")); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Ayam Rica-Rica : Rp 45.000");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(51, 153, 0));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Pictures\\Saved Pictures\\Nasi Campur.jpg")); // NOI18N
        jLabel15.setText("jLabel15");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Nasi Campur : Rp 20.000");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 153, 0));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Pictures\\Saved Pictures\\nasi goreng.jpg")); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Nasi Goreng : Rp 10.000");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btnPESAN.setBackground(new java.awt.Color(204, 255, 204));
        btnPESAN.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnPESAN.setForeground(new java.awt.Color(0, 102, 0));
        btnPESAN.setText("PESAN");
        btnPESAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPESANActionPerformed(evt);
            }
        });

        txtTANGGAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTANGGALActionPerformed(evt);
            }
        });

        jLabel27.setText("No Transaksi :");

        txtNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOActionPerformed(evt);
            }
        });

        jTable2.setBackground(new java.awt.Color(204, 255, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Transaksi", "Tanggal", "Nama", "Harga", "Jumlah", "Total", "Neto", "Bayar ", "Kembalian"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel12.setText("Tanggal :");

        btnHAPUSRIWAYAT.setBackground(new java.awt.Color(204, 255, 204));
        btnHAPUSRIWAYAT.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnHAPUSRIWAYAT.setForeground(new java.awt.Color(0, 102, 0));
        btnHAPUSRIWAYAT.setText("HAPUS RIWAYAT");
        btnHAPUSRIWAYAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHAPUSRIWAYATActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(333, 333, 333)
                                            .addComponent(btnBABI, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(16, 16, 16)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel12)
                                                        .addGap(43, 43, 43)
                                                        .addComponent(txtTANGGAL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel25))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(88, 88, 88)
                                                        .addComponent(btnIKAN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel27)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtNO, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(btnPROSES, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnHITUNG, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel11)
                                                                .addGap(18, 18, 18)))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(txtKEMBALI)
                                                            .addComponent(txtBAYAR, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(65, 65, 65)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnBATAL, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnPESAN, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(317, 317, 317)
                                                .addComponent(btnOKE5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTOTAL5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGap(317, 317, 317)
                                                    .addComponent(btnOKE4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtTOTAL4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtTOTAL3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnOKE2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtTOTAL2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel3)
                                                                .addGap(68, 68, 68)
                                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGap(0, 1, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(txtDAFTAR1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(txtDAFTAR2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(txtDAFTAR3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(txtDAFTAR4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(txtDAFTAR5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(txtHARGA2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGroup(layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(txtHARGA1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(txtHARGA3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(txtHARGA4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(txtHARGA5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addGroup(layout.createSequentialGroup()
                                                                                .addGap(29, 29, 29)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                    .addComponent(txtJUMLAH4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                    .addComponent(txtJUMLAH1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                    .addComponent(txtJUMLAH2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                    .addComponent(txtJUMLAH5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                    .addComponent(txtJUMLAH3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnOKE1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtTOTAL1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(btnOKE3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGap(86, 86, 86)
                                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                    .addComponent(jLabel1))))
                                        .addGap(18, 18, 18))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(138, 138, 138)
                                .addComponent(jLabel7)
                                .addGap(338, 338, 338)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(btnAYAM, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(195, 195, 195)
                                .addComponent(btnNASICAMPUR, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(194, 194, 194)
                                .addComponent(btnNASIGORENG, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnHAPUSRIWAYAT, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(538, 538, 538)
                                        .addComponent(btnKELUAR, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(1186, 1186, 1186))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTANGGAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIKAN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAYAM, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBABI, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNASICAMPUR, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNASIGORENG, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(btnKELUAR)
                    .addComponent(btnHAPUSRIWAYAT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHARGA1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtJUMLAH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnOKE1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTOTAL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDAFTAR1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDAFTAR2)
                            .addComponent(txtHARGA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJUMLAH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOKE2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTOTAL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDAFTAR3)
                            .addComponent(txtHARGA3)
                            .addComponent(txtJUMLAH4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOKE3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTOTAL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTOTAL4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtJUMLAH3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHARGA4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnOKE4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDAFTAR4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDAFTAR5)
                            .addComponent(txtHARGA5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJUMLAH5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOKE5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTOTAL5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPROSES, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBATAL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBAYAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(btnPESAN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHITUNG, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtKEMBALI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2215, 2215, 2215)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(758, 758, 758)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(520, 520, 520)
                                .addComponent(jLabel5)))
                        .addGap(399, 399, 399))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnIKANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIKANActionPerformed
          if(txtDAFTAR1.getText().isEmpty()) {
            txtDAFTAR1.setText("Ikan Panggang");
            txtHARGA1.setText("25000");
        } else if(txtDAFTAR2.getText().isEmpty()) {
            txtDAFTAR2.setText("Ikan Panggang");
            txtHARGA2.setText("25000");
        } else if(txtDAFTAR3.getText().isEmpty()) {
            txtDAFTAR3.setText("Ikan Panggang");
            txtHARGA3.setText("25000");
        } else if(txtDAFTAR4.getText().isEmpty()) {
            txtDAFTAR4.setText("Ikan Panggang");
            txtHARGA4.setText("25000");
        } else if(txtDAFTAR5.getText().isEmpty()) {
            txtDAFTAR5.setText("Ikan Panggang");
            txtHARGA5.setText("25000");
        }
       
    }//GEN-LAST:event_btnIKANActionPerformed

    private void btnBABIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBABIActionPerformed
         if(txtDAFTAR1.getText().isEmpty()) {
            txtDAFTAR1.setText("Babi Panggang");
            txtHARGA1.setText("40000");
        } else if(txtDAFTAR2.getText().isEmpty()) {
            txtDAFTAR2.setText("Babi Panggang");
            txtHARGA2.setText("40000");
        } else if(txtDAFTAR3.getText().isEmpty()) {
            txtDAFTAR3.setText("Babi Panggang");
            txtHARGA3.setText("40000");
        } else if(txtDAFTAR4.getText().isEmpty()) {
            txtDAFTAR4.setText("Babi Panggang");
            txtHARGA4.setText("40000");
        } else if(txtDAFTAR5.getText().isEmpty()) {
            txtDAFTAR5.setText("Babi Panggang");
            txtHARGA5.setText("40000");
        }
    }//GEN-LAST:event_btnBABIActionPerformed

    private void btnAYAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAYAMActionPerformed
        if(txtDAFTAR1.getText().isEmpty()) {
            txtDAFTAR1.setText("Ayam Rica Rica");
            txtHARGA1.setText("45000");
        } else if(txtDAFTAR2.getText().isEmpty()) {
            txtDAFTAR2.setText("Ayam Rica Rica");
            txtHARGA2.setText("45000");
        } else if(txtDAFTAR3.getText().isEmpty()) {
            txtDAFTAR3.setText("Ayam Rica Rica");
            txtHARGA3.setText("45000");
        } else if(txtDAFTAR4.getText().isEmpty()) {
            txtDAFTAR4.setText("Ayam Rica Rica");
            txtHARGA4.setText("45000");
        } else if(txtDAFTAR5.getText().isEmpty()) {
            txtDAFTAR5.setText("Ayam Rica Rica");
            txtHARGA5.setText("45000");
        }
    }//GEN-LAST:event_btnAYAMActionPerformed

    private void btnNASICAMPURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNASICAMPURActionPerformed
        if(txtDAFTAR1.getText().isEmpty()) {
            txtDAFTAR1.setText("Nasi Campur");
            txtHARGA1.setText("20000");
        } else if(txtDAFTAR2.getText().isEmpty()) {
            txtDAFTAR2.setText("Nasi Campur");
            txtHARGA2.setText("20000");
        } else if(txtDAFTAR3.getText().isEmpty()) {
            txtDAFTAR3.setText("Nasi Campur");
            txtHARGA3.setText("20000");
        } else if(txtDAFTAR4.getText().isEmpty()) {
            txtDAFTAR4.setText("Nasi Campur");
            txtHARGA4.setText("20000");
        } else if(txtDAFTAR5.getText().isEmpty()) {
            txtDAFTAR5.setText("Nasi Campur");
            txtHARGA5.setText("20000");
        }
    }//GEN-LAST:event_btnNASICAMPURActionPerformed

    private void btnNASIGORENGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNASIGORENGActionPerformed
        if(txtDAFTAR1.getText().isEmpty()) {
            txtDAFTAR1.setText("Nasi Goreng");
            txtHARGA1.setText("10000");
        } else if(txtDAFTAR2.getText().isEmpty()) {
            txtDAFTAR2.setText("Nasi Goreng");
            txtHARGA2.setText("10000");
        } else if(txtDAFTAR3.getText().isEmpty()) {
            txtDAFTAR3.setText("Nasi Goreng");
            txtHARGA3.setText("10000");
        } else if(txtDAFTAR4.getText().isEmpty()) {
            txtDAFTAR4.setText("Nasi Goreng");
            txtHARGA4.setText("10000");
        } else if(txtDAFTAR5.getText().isEmpty()) {
            txtDAFTAR5.setText("Nasi Goreng");
            txtHARGA5.setText("10000");
        }
    }//GEN-LAST:event_btnNASIGORENGActionPerformed

    private void btnOKE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKE1ActionPerformed
         row1 = Integer.parseInt(txtHARGA1.getText())*Integer.parseInt(txtJUMLAH1.getText());
        
        txtTOTAL1.setText(""+row1);
    }//GEN-LAST:event_btnOKE1ActionPerformed

    private void btnOKE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKE2ActionPerformed
         row2 = Integer.parseInt(txtHARGA2.getText())*Integer.parseInt(txtJUMLAH2.getText());
        
        txtTOTAL2.setText(""+row2);

    }//GEN-LAST:event_btnOKE2ActionPerformed

    private void btnOKE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKE3ActionPerformed
        row3 = Integer.parseInt(txtHARGA3.getText())*Integer.parseInt(txtJUMLAH3.getText());
        
        txtTOTAL3.setText(""+row3);
    }//GEN-LAST:event_btnOKE3ActionPerformed

    private void btnOKE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKE4ActionPerformed
        row4 = Integer.parseInt(txtHARGA4.getText())*Integer.parseInt(txtJUMLAH4.getText());
        
        txtTOTAL4.setText(""+row4);

    }//GEN-LAST:event_btnOKE4ActionPerformed

    private void btnOKE5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKE5ActionPerformed
        row5 = Integer.parseInt(txtHARGA5.getText())*Integer.parseInt(txtJUMLAH5.getText());
        
        txtTOTAL5.setText(""+row5);

    }//GEN-LAST:event_btnOKE5ActionPerformed

    private void btnPROSESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPROSESActionPerformed
         TotalSemua =(int) (row1+row2+row3+row4+row5);
         
         txtTOTAL.setText(""+TotalSemua);
    }//GEN-LAST:event_btnPROSESActionPerformed

    private void btnHITUNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHITUNGActionPerformed
        double Uang,Kembalian,bayar;
        
        Uang=Double.parseDouble(txtBAYAR.getText());
        bayar=Double.parseDouble(txtTOTAL.getText());
        Kembalian=Uang-bayar;
        
        if (Kembalian < 0){
            JOptionPane.showMessageDialog(null,"Uang Anda kurang sebesar Rp."+Kembalian*-1);
        } 
        else {
            txtKEMBALI.setText(""+Kembalian);
        }
      
        
    }//GEN-LAST:event_btnHITUNGActionPerformed

    private void btnBATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBATALActionPerformed
        txtDAFTAR1.setText("");
        txtDAFTAR2.setText("");
        txtDAFTAR3.setText("");
        txtDAFTAR4.setText("");
        txtDAFTAR5.setText("");
        txtHARGA1.setText("");
        txtHARGA2.setText("");
        txtHARGA3.setText("");
        txtHARGA4.setText("");
        txtHARGA5.setText("");
        txtJUMLAH1.setText("");
        txtJUMLAH2.setText("");
        txtJUMLAH3.setText("");
        txtJUMLAH4.setText("");
        txtJUMLAH5.setText("");
        txtKEMBALI.setText("");
        txtTOTAL.setText("");
        txtTOTAL1.setText("");
        txtTOTAL2.setText("");
        txtTOTAL3.setText("");
        txtTOTAL4.setText("");
        txtTOTAL5.setText("");
        txtBAYAR.setText("");
        
        
    }//GEN-LAST:event_btnBATALActionPerformed

    private void btnKELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKELUARActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKELUARActionPerformed

    private void txtJUMLAH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJUMLAH2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJUMLAH2ActionPerformed

    private void txtJUMLAH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJUMLAH5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJUMLAH5ActionPerformed

    private void txtTOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTOTALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTOTALActionPerformed

    private void btnPESANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPESANActionPerformed
        String no, tanggal, nama, harga, jumlah, total, neto, bayar, kembalian;
        no = txtNO.getText();
        tanggal = txtTANGGAL.getText();
        nama = txtDAFTAR1.getText()+" "+ txtDAFTAR2.getText()+" "+ txtDAFTAR3.getText()+" "+ txtDAFTAR4.getText()+" "+ txtDAFTAR5.getText();
        harga = txtHARGA1.getText()+" "+ txtHARGA2.getText()+" "+txtHARGA3.getText()+" "+txtHARGA4.getText()+" "+txtHARGA5.getText();
        jumlah = txtJUMLAH1.getText()+" "+txtJUMLAH2.getText()+" "+txtJUMLAH3.getText()+" "+txtJUMLAH4.getText()+" "+txtJUMLAH5.getText();
        total = txtTOTAL1.getText()+" "+txtTOTAL2.getText()+" "+txtTOTAL3.getText()+" "+txtTOTAL4.getText()+" "+txtTOTAL5.getText();
        neto = txtTOTAL.getText();
        bayar = txtBAYAR.getText();
        kembalian = txtKEMBALI.getText();
  
        addDatabase(no, tanggal, nama, harga, jumlah, total, neto, bayar, kembalian);
        viewtable();
        
        
        
    }//GEN-LAST:event_btnPESANActionPerformed

    private void txtNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOActionPerformed
   
    private void txtTANGGALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTANGGALActionPerformed
        Date ys=new Date(); 
        SimpleDateFormat s=new SimpleDateFormat("dd-MM-yyyy");
        txtTANGGAL.setText(s.format(ys));
    }//GEN-LAST:event_txtTANGGALActionPerformed

    private void btnHAPUSRIWAYATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHAPUSRIWAYATActionPerformed
        int jawab;
        try{
            if((jawab = JOptionPane.showConfirmDialog(null, "Ingin Hapus?","Konfirmasi",JOptionPane.YES_NO_OPTION))==0){
                stat.executeUpdate("DELETE FROM tb_resto");
                viewtable();
            }    
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_btnHAPUSRIWAYATActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(faulinaindri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(faulinaindri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(faulinaindri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(faulinaindri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new faulinaindri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAYAM;
    private javax.swing.JButton btnBABI;
    private javax.swing.JButton btnBATAL;
    private javax.swing.JButton btnHAPUSRIWAYAT;
    private javax.swing.JButton btnHITUNG;
    private javax.swing.JButton btnIKAN;
    private javax.swing.JButton btnKELUAR;
    private javax.swing.JButton btnNASICAMPUR;
    private javax.swing.JButton btnNASIGORENG;
    private javax.swing.JButton btnOKE1;
    private javax.swing.JButton btnOKE2;
    private javax.swing.JButton btnOKE3;
    private javax.swing.JButton btnOKE4;
    private javax.swing.JButton btnOKE5;
    private javax.swing.JButton btnPESAN;
    private javax.swing.JButton btnPROSES;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField txtBAYAR;
    private javax.swing.JTextField txtDAFTAR1;
    private javax.swing.JTextField txtDAFTAR2;
    private javax.swing.JTextField txtDAFTAR3;
    private javax.swing.JTextField txtDAFTAR4;
    private javax.swing.JTextField txtDAFTAR5;
    private javax.swing.JTextField txtHARGA1;
    private javax.swing.JTextField txtHARGA2;
    private javax.swing.JTextField txtHARGA3;
    private javax.swing.JTextField txtHARGA4;
    private javax.swing.JTextField txtHARGA5;
    private javax.swing.JTextField txtJUMLAH1;
    private javax.swing.JTextField txtJUMLAH2;
    private javax.swing.JTextField txtJUMLAH3;
    private javax.swing.JTextField txtJUMLAH4;
    private javax.swing.JTextField txtJUMLAH5;
    private javax.swing.JTextField txtKEMBALI;
    private javax.swing.JTextField txtNO;
    private javax.swing.JTextField txtTANGGAL;
    private javax.swing.JTextField txtTOTAL;
    private javax.swing.JTextField txtTOTAL1;
    private javax.swing.JTextField txtTOTAL2;
    private javax.swing.JTextField txtTOTAL3;
    private javax.swing.JTextField txtTOTAL4;
    private javax.swing.JTextField txtTOTAL5;
    // End of variables declaration//GEN-END:variables
}
